# Generated by Django 4.2.5 on 2024-03-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_gallery_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='English'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Русский'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Uzbekcha'),
        ),
    ]
