# Generated by Django 4.2.5 on 2024-03-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_category_button'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='link',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='button',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
