# Generated by Django 4.2.5 on 2024-03-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_tag_rename_content_news_text_news_created_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='text',
            new_name='text_en',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='news',
            name='text_ru',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='text_uz',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
