# Generated by Django 4.2.5 on 2024-03-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_quote_alter_news_options_alter_tag_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='photo',
            field=models.ImageField(default=1, upload_to='gallery_photos/'),
            preserve_default=False,
        ),
    ]
