# Generated by Django 4.2.5 on 2024-03-26 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_quote_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'verbose_name': 'цитата', 'verbose_name_plural': 'цитаты'},
        ),
    ]
