# Generated by Django 5.0.3 on 2024-04-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_employee_sertificateforemployee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='full_name_en',
            field=models.CharField(max_length=255, verbose_name='*ФИО(en)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name_ru',
            field=models.CharField(max_length=255, verbose_name='*ФИО(ru)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name_uz',
            field=models.CharField(max_length=255, verbose_name='*ФИО(uz)'),
        ),
    ]
