# Generated by Django 5.0.3 on 2024-04-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_alter_employee_full_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='about_en',
            field=models.TextField(default=1, max_length=255, verbose_name='*Инфо(en)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='about_ru',
            field=models.TextField(default=12, max_length=255, verbose_name='*Инфо(ru)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='about_uz',
            field=models.TextField(max_length=255, verbose_name='*Инфо(uz)'),
        ),
    ]
