# Generated by Django 5.0.3 on 2024-04-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_employee_about_en_employee_about_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sertificateforemployee',
            old_name='news',
            new_name='employee',
        ),
        migrations.AlterField(
            model_name='employee',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Инстаграм'),
        ),
    ]
