# Generated by Django 5.0.3 on 2024-04-09 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_rename_news_sertificateforemployee_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=255, verbose_name='*Заголовка(uz)')),
                ('title_en', models.CharField(max_length=255, verbose_name='*Заголовка(en)')),
                ('title_ru', models.CharField(max_length=255, verbose_name='*Заголовка(ru)')),
                ('body_uz', models.TextField(max_length=255, verbose_name='Текст(uz)')),
                ('body_en', models.TextField(max_length=255, verbose_name='Текст(en)')),
                ('body_ru', models.TextField(max_length=255, verbose_name='Текст(ru)')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='FileForDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Названия')),
                ('file', models.FileField(upload_to='documents/')),
                ('documente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Document', to='backend.document')),
            ],
        ),
    ]
