# Generated by Django 5.0.3 on 2024-04-16 10:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_alter_employee_about_en_alter_employee_about_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='about_en',
            field=ckeditor.fields.RichTextField(verbose_name='*Инфо(en)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='about_uz',
            field=ckeditor.fields.RichTextField(verbose_name='*Инфо(uz)'),
        ),
    ]
