# Generated by Django 5.0.3 on 2024-04-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_alter_employee_about_en_alter_employee_about_uz'),
    ]

    operations = [
        migrations.AddField(
            model_name='sertificateforemployee',
            name='queue',
            field=models.IntegerField(default=-1, verbose_name='Очеред показа(Необязательно)'),
        ),
    ]
