# Generated by Django 5.0.3 on 2024-04-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_sertificateforemployee_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sertificateforemployee',
            name='queue',
            field=models.IntegerField(default=10, verbose_name='Очеред показа(Необязательно)'),
        ),
    ]
