# Generated by Django 5.0.3 on 2024-04-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_alter_sertificateforemployee_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(upload_to='employee_photos/'),
        ),
    ]
