# Generated by Django 3.2.18 on 2024-04-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_alter_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sertificateforemployee',
            name='queue',
            field=models.IntegerField(default=1, verbose_name='Очеред показа(Необязательно)'),
        ),
    ]
