# Generated by Django 3.2.18 on 2024-04-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_alter_sertificateforemployee_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook(link)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Инстаграм(link)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='Телеграм(https://t.me/username)'),
        ),
    ]
