# Generated by Django 5.0.3 on 2024-05-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_qabul_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qabul',
            name='passport',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
