# Generated by Django 5.0.3 on 2024-05-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_alter_qabul_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qabul',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
