# Generated by Django 3.2.18 on 2024-05-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'заявка', 'verbose_name_plural': 'заявки'},
        ),
        migrations.AlterModelOptions(
            name='qabul',
            options={'verbose_name': 'приём', 'verbose_name_plural': 'приём'},
        ),
        migrations.AddField(
            model_name='contact',
            name='directions',
            field=models.CharField(choices=[("Boshlang'ich ta'lim", "Boshlang'ich ta'lim"), ('Tarix', 'Tarix'), ("Filoligiya va tillarni o'qitish(O'zbek tili)", "Filoligiya va tillarni o'qitish(O'zbek tili)"), ("Filoligiya va tillarni o'qitish(Ingliz tili)", "Filoligiya va tillarni o'qitish(Ingliz tili)")], default="Boshlangich ta'lim", max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='education_type',
            field=models.CharField(choices=[('full_time', 'Очное'), ('part_time', 'Заочное')], default='part_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=15, unique=True, verbose_name='Телефон'),
        ),
    ]
