# Generated by Django 5.0.3 on 2024-05-24 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_alter_contact_education_type_alter_qabul_directions'),
        ('backend', '0044_auto_20240524_1553'),
    ]

    operations = [
    ]
