# Generated by Django 3.2.18 on 2024-05-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0046_rename_address_qabul_kucha_qabul_mfy_qabul_tuman_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
