# Generated by Django 3.2.18 on 2024-06-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0047_contact_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='qabul',
            name='attestat',
            field=models.CharField(default=121, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qabul',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qabul',
            name='father',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qabul',
            name='father_address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qabul',
            name='father_job',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qabul',
            name='father_phone_number',
            field=models.CharField(default=12, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qabul',
            name='languages',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qabul',
            name='mother',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qabul',
            name='mother_address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qabul',
            name='mother_job',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qabul',
            name='mother_phone_number',
            field=models.CharField(default=21, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qabul',
            name='school',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
